name: Release

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: "The release version in <MAJOR>.<MINOR>.<PATCH> format"
        required: true
      nextVersion:
        description: "The next version in <MAJOR>.<MINOR> format WITHOUT SNAPSHOT SUFFIX"
        required: true

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: "Set release version in gradle.properties file"
        run: |
          sed -i -e '/version=/s/.*/version=${{ inputs.releaseVersion }}/g' gradle.properties
          cat gradle.properties
      - name: "Set next development version in gradle.properties file"
        run: |
          sed -i -e '/version=/s/.*/version=${{ inputs.nextVersion }}-SNAPSHOT/g' gradle.properties
          cat gradle.properties


